demo_getdbt:
  outputs:
    dev:
      dataset: getdbt_demo
      fixed_retries: 1
      keyfile: /home/gitpod/.dbt/dogwood-day-336418-28272a6c70e7.json
      location: US
      method: service-account
      priority: interactive
      project: dogwood-day-336418
      threads: 4
      timeout_seconds: 300
      type: bigquery
  target: dev


